### ISSUE TITLE
Roundcube plugin not working anymore

### ISSUE THREAD

**Issue by universenl** [dirkgroenen/Goldfish-Autoresponder#12]
After updating to the latest roundcube the plugin got like 500 errors:

`Notice: Undefined index: filesystem_attachments in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_plugin_api.php on line 167

Notice: Undefined index: jqueryui in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_plugin_api.php on line 167

Notice: Undefined variable: add in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db.php on line 935

Notice: Undefined index: w in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db.php on line 130

Notice: Undefined index: port in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db_mysql.php on line 95

Notice: Undefined index: socket in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db_mysql.php on line 99

Notice: Uninitialized string offset: 78 in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db.php on line 437

Notice: Undefined index: temp in /var/www/serv-ict.email/public_html/program/include/rcmail.php on line 490

Notice: Uninitialized string offset: 41 in /var/www/serv-ict.email/public_html/program/lib/Roundcube/rcube_db.php on line 437
`

Can anybody support on this ?

**Comment by dirkgroenen** [comment]
Those "errors" are actually notices and should not crash the application. You can turn them of in your php settings.
