### ISSUE TITLE
goldfish.php error force_disabled vs force_enabled

### ISSUE THREAD

**Issue by Bumblebee222** [dirkgroenen/Goldfish-Autoresponder#2]
Hi, 
Did you test your software on a fresh installation ? 

I find a few error, and don't seem to work... 

in your installation guide... database creation... 
`force_enabled` tinyint(4) NOT NULL default '0',
but in goldfish.php = 'force_disabled'

missing $ in front of... in roundcube config: 
rcmail_config['plugins'] = array('pluginx', 'autoreply');

need to add in crontab [...] php goldfish.php > /dev/null

> dev/null... for stop sending email..

i installed the plugin... but i receive a blank page when i hit "auto reply"

now work with the script... not with roundcube

**Comment by dirkgroenen** [comment]
I haven't test it on a fresh installation, but I don't think that should matter that much. Thanks for the noticing the typos in the readme, I've just fixed them. 

Does Roundcube produce any errors when you see the white page? Also check your webserver's error log if they don't appear on the page.

**Comment by Bumblebee222** [comment]
i search, didn't find any clue...i stop searching.
 now i'm using the _managesieve_ in the roundcube plugin. And work fine for auto-reply (vacation). 

If you want to use it on ubuntu/debian, i use this guide, but it's for centos.
https://www.rosehosting.com/blog/how-to-set-up-server-side-email-filtering-with-dovecot-sieve-and-roundcube-on-a-centos-6-vps/
